image: kindest/node:v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f

gardener:
  apiserverRelay:
    deployed: false
  controlPlane:
    deployed: true
    kindIsGardenCluster: true
    customEtcdStatefulSet: true
  nginxIngress:
    deployed: true
  seed:
    deployed: true
    istio:
      listenAddresses:
      - 172.18.255.1
    bastion:
      listenAddresses:
      - 172.18.255.22
  repositoryRoot: "."
  garden:
    deployed: false

backupBucket:
  deployed: true

registry:
  deployed: true

networking:
  ipFamily: ipv4
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.2.0.0/16

#workers:
#- zone: "1"
#- zone: "2"
